---
variables:
  - &file Backend_Py_Dockerfile
  - &dhub https://index.docker.io/v1/
  - &arch linux/arm64/v8
  - &repo bksolutions/test/backend-python




steps:
  build:
    when:
      - event: [push]
        branch: main
        path:
          include: ['/backend/python/Dockerfile', '.woodpecker/build_backend_py.yml']
      - event: [cron, manual]
        branch: main
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: true
      tags: 
        - 'latest'
      build_args:
        - VERSION="latest"
        - CREATED="${CI_PIPELINE_STARTED}"
        - REVISION="${CI_COMMIT_SHA}"
      output: type=oci,dest=BackendPython_${CI_PIPELINE_STARTED}_build.tar


  release:
    image: woodpeckerci/plugin-release
    settings:
      #api_key: ${GITHUB_TOKEN}      
      user: DOCKER_BKSOL_USER
      password: DOCKER_BKSOL_PASS
      title: "Backend Container Release, Python"
      tag: "v${CI_BUILD_NUMBER}"
      files:
        - BackendPython_${CI_PIPELINE_STARTED}_build.tar
    when:
      event: push
      branch: main
