
steps:
  build-container:
    image: docker:26-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""   # vereinfacht CLI-Nutzung im Container
      DOCKER_BUILDKIT: "1"
      #PLATFORM: linux/amd64
    commands:
      - dockerd-entrypoint.sh &
      - |
        # Warten bis der Docker-Daemon läuft
        for i in $(seq 1 30); do
          docker info >/dev/null 2>&1 && break
          sleep 1
        done
      - docker version
      - docker buildx inspect >/dev/null 2>&1 || docker buildx create --use
      # Für Cross-Arch Builds ist dind bereits privileged -> binfmt kann hier im Step installiert werden:
      - docker run --privileged --rm tonistiigi/binfmt --install all
      - |
        docker buildx build \
          --platform "${PLATFORM}" \
          -t my-python-app:latest \
          --output type=docker,dest=python-container.tar \
          .


    when:
      event: push

  release:
    image: woodpeckerci/plugin-github-release
    settings:
      #api_key: ${GITHUB_TOKEN}      
      user: DOCKER_BKSOL_USER
      password: DOCKER_BKSOL_PASS
      title: "Python Container Release"
      tag: "v${CI_BUILD_NUMBER}"
      files:
        - python-container.tar
    when:
      event: push
      branch: main
